web:
  build: .
  ports:
   - "8000:80"
  links:
   - db
  volumes:
   - .:/app
db:
  image: mysql
  ports:
   - "3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
